### ISSUE TITLE
failed to generate onnx model use provided python script.

### ISSUE THREAD

**Issue by julinfn** [mingj2021/segment-anything-tensorrt#1]
wonderful work! i failed to generate model use python script,error msg like this.      would you share tensorrt model of vit-b or vit-l? in consider of efficiency,vit-b may be more suitable for real-time cases.
```

[04/26/2023-17:28:32] [TRT] [E] ModelImporter.cpp:776: --- End node ---
[04/26/2023-17:28:32] [TRT] [E] ModelImporter.cpp:779: ERROR: ModelImporter.cpp:163 In function parseGraph:
[6] Invalid Node - node_of_/patch_embed/proj/Conv_output_0_bias_reshape_output
Attribute not found: allowzero
Traceback (most recent call last):
  File "e:\git\paddle\segment-anything\exportRT.py", line 117, in <module>
    export_engine_image_encoder('encoder-quant.onnx')
  File "e:\git\paddle\segment-anything\exportRT.py", line 101, in export_engine_image_encoder
    raise RuntimeError(f'failed to load ONNX file: {onnx}')
RuntimeError: failed to load ONNX file: encoder-quant.onnx
PS E:\git\paddle\segment-anything> & D:/profProgram/python3912/python.exe e:/git/paddle/segment-anything/exportRT.py
image_embeddings (1, 256, 64, 64)
e:\git\paddle\segment-anything\segment_anything\modeling\image_encoder.py:258: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if pad_h > 0 or pad_w > 0:
e:\git\paddle\segment-anything\segment_anything\modeling\image_encoder.py:262: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').      
  x = x.view(B, Hp // window_size, window_size, Wp // window_size, window_size, C)
e:\git\paddle\segment-anything\segment_anything\modeling\image_encoder.py:304: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  max_rel_dist = int(2 * max(q_size, k_size) - 1)
e:\git\paddle\segment-anything\segment_anything\modeling\image_encoder.py:304: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  max_rel_dist = int(2 * max(q_size, k_size) - 1)
e:\git\paddle\segment-anything\segment_anything\modeling\image_encoder.py:306: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if rel_pos.shape[0] != max_rel_dist:
e:\git\paddle\segment-anything\segment_anything\modeling\image_encoder.py:318: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  q_coords = torch.arange(q_size)[:, None] * max(k_size / q_size, 1.0)
e:\git\paddle\segment-anything\segment_anything\modeling\image_encoder.py:319: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  k_coords = torch.arange(k_size)[None, :] * max(q_size / k_size, 1.0)
e:\git\paddle\segment-anything\segment_anything\modeling\image_encoder.py:320: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  relative_coords = (q_coords - k_coords) + (k_size - 1) * max(q_size / k_size, 1.0)
e:\git\paddle\segment-anything\segment_anything\modeling\image_encoder.py:283: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').      
  B = windows.shape[0] // (Hp * Wp // window_size // window_size)
e:\git\paddle\segment-anything\segment_anything\modeling\image_encoder.py:284: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').      
  x = windows.view(B, Hp // window_size, Wp // window_size, window_size, window_size, -1)
e:\git\paddle\segment-anything\segment_anything\modeling\image_encoder.py:287: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if Hp > H or Wp > W:
```

**Comment by mingj2021** [comment]
try this the demo script "demo.py"  to generate onnx or engine model,  Decompose the official model into two onnx submodels, one for embeddings, another for "prompt and mask decoder".

**Comment by mingj2021** [comment]
Currently, only the lefp32 engine is tested

**Comment by mingj2021** [comment]
.engine(fp32) model  https://drive.google.com/drive/folders/1FXmWw80bwcwMnmPLRS0h70HR_SY1K1RG?usp=share_link

**Comment by mingj2021** [comment]
change opt_version to 13 ,and try agian!
