### ISSUE TITLE
AttributeError: __enter__

### ISSUE THREAD

**Issue by Jorbo19** [mingj2021/segment-anything-tensorrt#5]
[05/25/2023-15:12:34] [TRT] [I] [MemUsageChange] Init CUDA: CPU +272, GPU +0, now: CPU 6872, GPU 1126 (MiB)
[05/25/2023-15:12:35] [TRT] [I] [MemUsageSnapshot] Begin constructing builder kernel library: CPU 6937 MiB, GPU 1126 MiB
[05/25/2023-15:12:35] [TRT] [I] [MemUsageSnapshot] End constructing builder kernel library: CPU 6998 MiB, GPU 1126 MiB
workspace:  6
[05/25/2023-15:12:35] [TRT] [I] ----------------------------------------------------------------
[05/25/2023-15:12:35] [TRT] [I] Input filename:   sam_onnx_example.onnx
[05/25/2023-15:12:35] [TRT] [I] ONNX IR version:  0.0.0
[05/25/2023-15:12:35] [TRT] [I] Opset version:    0
[05/25/2023-15:12:35] [TRT] [I] Producer name:    
[05/25/2023-15:12:35] [TRT] [I] Producer version: 
[05/25/2023-15:12:35] [TRT] [I] Domain:           
[05/25/2023-15:12:35] [TRT] [I] Model version:    0
[05/25/2023-15:12:35] [TRT] [I] Doc string:       
[05/25/2023-15:12:35] [TRT] [I] ----------------------------------------------------------------
building FP32 engine as sam_onnx_example.engine
[05/25/2023-15:12:35] [TRT] [E] 4: [network.cpp::nvinfer1::Network::validate::2633] Error Code 4: Internal Error (Network must have at least one output)
E:/pose/segment-anything/notebooks/demo.py:311: DeprecationWarning: Use build_serialized_network instead.
  with builder.build_engine(network, config) as engine, open(f, 'wb') as t:
Traceback (most recent call last):
  File "E:/pose/segment-anything/notebooks/demo.py", line 432, in <module>
    export_engine_prompt_encoder_and_mask_decoder()
  File "E:/pose/segment-anything/notebooks/demo.py", line 311, in export_engine_prompt_encoder_and_mask_decoder
    with builder.build_engine(network, config) as engine, open(f, 'wb') as t:
AttributeError: __enter__

Can you help me？

**Comment by mingj2021** [comment]
firstly ,change opset_version(14,15,16,17), and try again

**Comment by Jorbo19** [comment]
sorry，I tested the version as （14,15,16,17），but the problem remains ,my version onnxruntime-1.14.1，tensorrt-8.2.3

**Comment by mingj2021** [comment]
build with docker please, the repos has been strictly tested in docker.on other dev environment, only simple test.
